// librarian.h
// Generated by The Librarian
// Copyleft 2012 The Mojon Twins
 
typedef struct {
   unsigned char ramPage;
   unsigned int ramOffset;
} RESOURCE;
 
RESOURCE resources [] = {
   {3, 49152},   // 0: title.bin
   {3, 51629},   // 1: marco.bin
   {3, 51965},   // 2: ending.bin
   {3, 52023},   // 3: map0c.bin
   {3, 52542},   // 4: bolts0c.bin
   {3, 52548},   // 5: ts0c.bin
   {3, 53169},   // 6: ss0c.bin
   {3, 53738},   // 7: enems0c.bin
   {3, 53919},   // 8: hotspots0c.bin
   {3, 53929},   // 9: behs0c.bin
   {3, 53947},   // 10: map1c.bin
   {3, 54428},   // 11: bolts1c.bin
   {3, 54434},   // 12: ts1c.bin
   {3, 55557},   // 13: ss1c.bin
   {3, 56178},   // 14: enems1c.bin
   {3, 56359},   // 15: hotspots1c.bin
   {3, 56375},   // 16: behs1c.bin
   {3, 56400},   // 17: map2c.bin
   {3, 56874},   // 18: bolts2c.bin
   {3, 56880},   // 19: ts2c.bin
   {3, 57706},   // 20: ss2c.bin
   {3, 58257},   // 21: enems2c.bin
   {3, 58404},   // 22: hotspots2c.bin
   {3, 58420},   // 23: behs2c.bin
   {3, 58438},   // 24: map3c.bin
   {3, 59190},   // 25: bolts3c.bin
   {3, 59196},   // 26: ts3c.bin
   {3, 59759},   // 27: enems3c.bin
   {3, 59970},   // 28: hotspots3c.bin
   {3, 59980},   // 29: behs3c.bin
   {3, 59999},   // 30: map4c.bin
   {3, 60441},   // 31: bolts4c.bin
   {3, 60447},   // 32: ts4c.bin
   {3, 61383},   // 33: ss4c.bin
   {3, 61981},   // 34: enems4c.bin
   {3, 62143},   // 35: hotspots4c.bin
   {3, 62160},   // 36: behs4c.bin
   {3, 62180},   // 37: map5c.bin
   {3, 62847},   // 38: bolts5c.bin
   {3, 62853},   // 39: ts5c.bin
   {3, 64063},   // 40: enems5c.bin
   {3, 64278},   // 41: hotspots5c.bin
   {3, 64291},   // 42: behs5c.bin
   {3, 64315},   // 43: bolts8c.bin
   {3, 64321},   // 44: enems8c.bin
   {3, 64591},   // 45: hotspots8c.bin
   {3, 64605},   // 46: behs8c.bin
   {3, 64632},   // 47: enems6c.bin
   {3, 64896},   // 48: hotspots6c.bin
   {3, 64906},   // 49: bolts6c.bin
   {3, 64912},   // 50: bolts9c.bin
   {3, 64918},   // 51: boltsBc.bin
   {3, 64924},   // 52: bolts7c.bin
   {3, 64930},   // 53: boltsAc.bin
   {3, 64936},   // 54: boltsDc.bin
   {3, 64942},   // 55: boltsCc.bin
   {3, 64948},   // 56: boltsEc.bin
   {3, 64954},   // 57: enems9c.bin
   {3, 65145},   // 58: hotspots9c.bin
   {3, 65157},   // 59: behs9c.bin
   {3, 65187},   // 60: enemsBc.bin
   {3, 65207},   // 61: hotspotsBc.bin
   {3, 65214},   // 62: behsBc.bin
   {3, 65235},   // 63: enems7c.bin
   {4, 49152},   // 64: hotspots7c.bin
   {4, 49174},   // 65: enemsAc.bin
   {4, 49442},   // 66: hotspotsAc.bin
   {4, 49459},   // 67: behsAc.bin
   {4, 49480},   // 68: ts8c.bin
   {4, 50722},   // 69: map8c.bin
   {4, 51472},   // 70: map6c.bin
   {4, 52042},   // 71: map9c.bin
   {4, 52551},   // 72: ts9c.bin
   {4, 53662},   // 73: mapBc.bin
   {4, 54029},   // 74: tsBc.bin
   {4, 55146},   // 75: map7c.bin
   {4, 55853},   // 76: mapAc.bin
   {4, 56494},   // 77: tsAc.bin
   {4, 57465},   // 78: mapDc.bin
   {4, 57850},   // 79: enemsDc.bin
   {4, 57960},   // 80: hotspotsDc.bin
   {4, 57971},   // 81: mapCc.bin
   {4, 58286},   // 82: tsCc.bin
   {4, 58989},   // 83: enemsCc.bin
   {4, 59114},   // 84: hotspotsCc.bin
   {4, 59123},   // 85: behsCc.bin
   {4, 59145},   // 86: mapEc.bin
   {4, 59691},   // 87: enemsEc.bin
   {4, 60014},   // 88: hotspotsEc.bin
   {4, 60035},   // 89: mapFc.bin
   {4, 60618},   // 90: enemsFc.bin
   {4, 60808},   // 91: hotspotsFc.bin
   {4, 60823},   // 92: boltsFc.bin
   {4, 60829},   // 93: mapZc.bin
   {4, 61478},   // 94: boltsZc.bin
   {4, 61484},   // 95: ending1.bin
   {4, 62758},   // 96: enemsZc.bin
   {4, 62991},   // 97: hotspotsZc.bin
   {4, 63005},   // 98: behsZc.bin
   {4, 63036},   // 99: mapYc.bin
   {4, 63696},   // 100: boltsYc.bin
   {4, 63702},   // 101: tsYc.bin
   {4, 64314},   // 102: enemsYc.bin
   {4, 64636},   // 103: hotspotsYc.bin
   {4, 64659},   // 104: behsYc.bin
   {4, 64677},   // 105: mapXc.bin
   {4, 64742},   // 106: boltsXc.bin
   {4, 64748},   // 107: ending4.bin
   {4, 65078},   // 108: enemsXc.bin
   {4, 65088},   // 109: hotspotsXc.bin
   {4, 65096},   // 110: behsXc.bin
   {4, 65110},   // 111: dedicado.bin
   {6, 61223},   // 112: tsZc.bin
   {6, 62387},   // 113: level.bin
   {7, 60319},   // 114: credits.bin
   {7, 62047},   // 115: ending3.bin
   {7, 63246},   // 116: ending2.bin
   {7, 64482}    // 117: tsXc.bin
};
 
void get_resource (unsigned char res, unsigned int dest) {
   unpack_RAMn (resources [res].ramPage, resources [res].ramOffset, dest);
}
 
// Defines
#define TITLE_BIN           	0
#define MARCO_BIN           	1
#define ENDING_BIN          	2
#define MAP0C_BIN           	3
#define BOLTS0C_BIN         	4
#define TS0C_BIN            	5
#define SS0C_BIN            	6
#define ENEMS0C_BIN         	7
#define HOTSPOTS0C_BIN      	8
#define BEHS0C_BIN          	9
#define MAP1C_BIN           	10
#define BOLTS1C_BIN         	11
#define TS1C_BIN            	12
#define SS1C_BIN            	13
#define ENEMS1C_BIN         	14
#define HOTSPOTS1C_BIN      	15
#define BEHS1C_BIN          	16
#define MAP2C_BIN           	17
#define BOLTS2C_BIN         	18
#define TS2C_BIN            	19
#define SS2C_BIN            	20
#define ENEMS2C_BIN         	21
#define HOTSPOTS2C_BIN      	22
#define BEHS2C_BIN          	23
#define MAP3C_BIN           	24
#define BOLTS3C_BIN         	25
#define TS3C_BIN            	26
#define ENEMS3C_BIN         	27
#define HOTSPOTS3C_BIN      	28
#define BEHS3C_BIN          	29
#define MAP4C_BIN           	30
#define BOLTS4C_BIN         	31
#define TS4C_BIN            	32
#define SS4C_BIN            	33
#define ENEMS4C_BIN         	34
#define HOTSPOTS4C_BIN      	35
#define BEHS4C_BIN          	36
#define MAP5C_BIN           	37
#define BOLTS5C_BIN         	38
#define TS5C_BIN            	39
#define ENEMS5C_BIN         	40
#define HOTSPOTS5C_BIN      	41
#define BEHS5C_BIN          	42
#define BOLTS8C_BIN         	43
#define ENEMS8C_BIN         	44
#define HOTSPOTS8C_BIN      	45
#define BEHS8C_BIN          	46
#define ENEMS6C_BIN         	47
#define HOTSPOTS6C_BIN      	48
#define BOLTS6C_BIN         	49
#define BOLTS9C_BIN         	50
#define BOLTSBC_BIN         	51
#define BOLTS7C_BIN         	52
#define BOLTSAC_BIN         	53
#define BOLTSDC_BIN         	54
#define BOLTSCC_BIN         	55
#define BOLTSEC_BIN         	56
#define ENEMS9C_BIN         	57
#define HOTSPOTS9C_BIN      	58
#define BEHS9C_BIN          	59
#define ENEMSBC_BIN         	60
#define HOTSPOTSBC_BIN      	61
#define BEHSBC_BIN          	62
#define ENEMS7C_BIN         	63
#define HOTSPOTS7C_BIN      	64
#define ENEMSAC_BIN         	65
#define HOTSPOTSAC_BIN      	66
#define BEHSAC_BIN          	67
#define TS8C_BIN            	68
#define MAP8C_BIN           	69
#define MAP6C_BIN           	70
#define MAP9C_BIN           	71
#define TS9C_BIN            	72
#define MAPBC_BIN           	73
#define TSBC_BIN            	74
#define MAP7C_BIN           	75
#define MAPAC_BIN           	76
#define TSAC_BIN            	77
#define MAPDC_BIN           	78
#define ENEMSDC_BIN         	79
#define HOTSPOTSDC_BIN      	80
#define MAPCC_BIN           	81
#define TSCC_BIN            	82
#define ENEMSCC_BIN         	83
#define HOTSPOTSCC_BIN      	84
#define BEHSCC_BIN          	85
#define MAPEC_BIN           	86
#define ENEMSEC_BIN         	87
#define HOTSPOTSEC_BIN      	88
#define MAPFC_BIN           	89
#define ENEMSFC_BIN         	90
#define HOTSPOTSFC_BIN      	91
#define BOLTSFC_BIN         	92
#define MAPZC_BIN           	93
#define BOLTSZC_BIN         	94
#define ENDING1_BIN         	95
#define ENEMSZC_BIN         	96
#define HOTSPOTSZC_BIN      	97
#define BEHSZC_BIN          	98
#define MAPYC_BIN           	99
#define BOLTSYC_BIN         	100
#define TSYC_BIN            	101
#define ENEMSYC_BIN         	102
#define HOTSPOTSYC_BIN      	103
#define BEHSYC_BIN          	104
#define MAPXC_BIN           	105
#define BOLTSXC_BIN         	106
#define ENDING4_BIN         	107
#define ENEMSXC_BIN         	108
#define HOTSPOTSXC_BIN      	109
#define BEHSXC_BIN          	110
#define DEDICADO_BIN        	111
#define TSZC_BIN            	112
#define LEVEL_BIN           	113
#define CREDITS_BIN         	114
#define ENDING3_BIN         	115
#define ENDING2_BIN         	116
#define TSXC_BIN            	117
