..\utils\apack.exe mus\01_title!.mus 01_titlec.mus
..\utils\apack.exe mus\02_map!.mus 02_mapc.mus
..\utils\apack.exe mus\03_tutorial!.mus 03_tutorialc.mus
..\utils\apack.exe mus\04_level_1!!.mus 04_level_1c.mus
..\utils\apack.exe mus\05_level_2!.mus 05_level_2c.mus
..\utils\apack.exe mus\06_tiendas!.mus 06_tiendasc.mus
..\utils\apack.exe mus\07_level_3!.mus 07_level_3c.mus
..\utils\apack.exe mus\08_level_4!.mus 08_level_4c.mus
..\utils\apack.exe mus\09_stage_clear!.mus 09_stage_clearc.mus
..\utils\apack.exe mus\10_game_over!.mus 10_game_overc.mus
..\utils\apack.exe mus\11_lava_2!.mus 11_lavac.mus
..\utils\apack.exe mus\12_ending!.mus 12_endingc.mus
..\utils\apack.exe mus\13_bud_spencer!.mus 13_bud_spencerc.mus
..\utils\apack.exe mus\14_maikel_nait!.mus 14_maikel_naitc.mus
..\utils\apack.exe mus\15_cabesa!.mus 15_cabesac.mus
..\utils\apack.exe mus\16_mr_t!.mus 16_mr_tc.mus
..\utils\apack.exe mus\17_chuck_norris!.mus 17_chuck_norrisc.mus
..\utils\apack.exe mus\18_walker!.mus 18_walkerc.mus
..\utils\apack.exe mus\19_bruce_lee!.mus 19_bruce_leec.mus
..\utils\apack.exe mus\20_level_extra!.mus 20_playac.mus
..\utils\apack.exe mus\21_hacer_cosas!.mus 21_hacer_cosasc.mus
..\utils\apack.exe mus\22_rick_astley.mus 22_rick_astleyc.mus
