// msc-config.h
// Generated by Mojon Script Compiler v3.97 20191202 fromMT Engine MK2 v1.0+
// Copyleft 2014, 2019 The Mojon Twins

unsigned char sc_x, sc_y, sc_n, sc_m, sc_c;
unsigned char script_result = 0;
unsigned char sc_terminado = 0;
unsigned char sc_continuar = 0;
unsigned int main_script_offset;
#ifndef MODE_128K
extern unsigned char main_script [0];
#asm
    ._main_script
        BINARY "../bin/scripts.bin"
#endasm
#endif
unsigned char warp_to_level;
extern unsigned char *script;
#asm
    ._script defw 0
#endasm

#define LEVEL_TOWN 0x0000
#define LEVEL_SAROLLAN 0x0477
#define LEVEL_CASTLE_A 0x0806
#define LEVEL_SHOPS 0x0C14
#define LEVEL_OCTOPUS 0x129A
#define LEVEL_TUTORIAL 0x15E6
#define LEVEL_LAVA 0x185A
#define LEVEL_CASTLE_B 0x1988
#define LEVEL_ENDING_BAD 0x2409
#define LEVEL_ENDING_GOOD 0x2482
#define LEVEL_CLUB 0x26D6
#define SCRIPT_INIT 49152 
